Muqabalati.Web/Areas/Customer/Controllers/InterviewController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Muqabalati.Service.Interfaces;
using Muqabalati.Service.DTOs;
using Newtonsoft.Json;

namespace Muqabalati.Web.Controllers
{
    [Area("Customer")]
    public class InterviewController : Controller
    {
        private readonly IInterviewService _interviewService;
        private const string SessionKey = "InterviewSession";


        public InterviewController(IInterviewService interviewService)
        {
            _interviewService = interviewService;
        }

        [HttpGet]
        public IActionResult InterviewGenerator()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            InterviewRequestDto request = new();
            request.Topics = ["Machine Learning Engineer", "Software Developer", ".Net Developer", "Full-Stack Developer", "UI/UX Designer", "Graphic Designer", "Full-Stack Developer"];

            return View(request);
        }


        [HttpPost]
        public async Task<IActionResult> InterviewGenerator(InterviewRequestDto request)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var interviewSessionDto = await _interviewService.GenerateInterviewSessionAsync(request);
                    
                    // Store the session JSON in HttpContext.Session
                    HttpContext.Session.SetString(SessionKey, JsonConvert.SerializeObject(interviewSessionDto));

                    HttpContext.Session.SetString("tone", request.Tone);

                    return View("StartInterview", interviewSessionDto.Tone);

                }
                catch (System.Exception ex)
                {
                    return View("Error");
                }
            }

            request.Topics = new List<string> { "Machine Learning Engineer", "Software Developer", ".Net Developer", "Full-Stack Developer", "UI/UX Designer", "Graphic Designer", "Full-Stack Developer" };
            return View(request);
            
        }


        [HttpGet]
        public async Task<IActionResult> StartInterview()
        {
            return View();
        }


      
        [HttpGet]
        public async Task<IActionResult> InterviewResult()
        {

            if (TempData["InterviewReport"] is string ratingJson)
            {
                var report = JsonConvert.DeserializeObject<InterviewReportDto>(ratingJson);

                return View("InterviewResult", report);
            }
            else
            {
                return RedirectToAction("InterviewGenerator");
                //return View("InterviewIsOver", "المقابلة لقد انتهت");
            }
        }

        [HttpGet]
        public IActionResult InterviewIsOver(string reason)
        {
            return View(reason);
        }
        
    }
}

Muqabalati.Web/Areas/Customer/Views/Interview/InterviewIsOver.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Muqabalati.Web/Areas/Customer/Views/Interview/InterviewResult.cshtml
@model InterviewReportDto
@{
    Layout = "_LayoutInterview.cshtml";
    ViewData["Title"] = "Interview Result";
}

@section Styles {
    <link rel="stylesheet" href="~/css/interview-resullt.css" asp-append-version="true" />

}

<div class="star_container down">
    <svg width="37"
    height="43"
    viewBox="0 0 37 43"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
        fill="#364C84" />
    </svg>
</div>
<div class="star_container middle-top">
    <svg width="37"
    height="43"
    viewBox="0 0 37 43"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
        fill="#364C84" />
    </svg>
</div>
<div class="star_container middle-right">
    <svg width="37"
    height="43"
    viewBox="0 0 37 43"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
        fill="#364C84" />
    </svg>
</div>

<section id="result-page" class="container">
    <div class="rate-sec row">
        <div class="result col">
            <div class="circle-container">
                <div class="circle @(Model.IsPassed ? "passed" : "failed") ">
                    <span>النتيجة</span>
                <span class="percentage @(Model.IsPassed ? "passed" : "failed")">@(Model.GPA)%</span>
                </div>
            </div>
            <div class="result-info">
                <h1 class=" @(Model.IsPassed ? "passed" : "failed")">@(Model.IsPassed ? "مقبول" : "مرفوض")</h1>
                <div class="answers-stats">
                    <div class="correct-answers">
                        <span class="label">
                            الإجابات الصحيحة
                        <svg width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                            <path d="M7.48047 18.35L10.5805 20.75C10.9805 21.15 11.8805 21.35 12.4805 21.35H16.2805C17.4805 21.35 18.7805 20.45 19.0805 19.25L21.4805 11.95C21.9805 10.55 21.0805 9.34997 19.5805 9.34997H15.5805C14.9805 9.34997 14.4805 8.84997 14.5805 8.14997L15.0805 4.94997C15.2805 4.04997 14.6805 3.04997 13.7805 2.74997C12.9805 2.44997 11.9805 2.84997 11.5805 3.44997L7.48047 9.54997"
                                    stroke="#E7F1A8"
                                    stroke-width="1.5"
                                    stroke-miterlimit="10" />
                            <path d="M2.37988 18.35V8.55002C2.37988 7.15002 2.97988 6.65002 4.37988 6.65002H5.37988C6.77988 6.65002 7.37988 7.15002 7.37988 8.55002V18.35C7.37988 19.75 6.77988 20.25 5.37988 20.25H4.37988C2.97988 20.25 2.37988 19.75 2.37988 18.35Z"
                                    stroke="#E7F1A8"
                                    stroke-width="1.5"
                                    stroke-linecap="round"
                                    stroke-linejoin="round" />
                            </svg>   
                        </span>    
                        <span>@Model.TotalQuestions / <span class="answers-count">@Model.CorrectAnswers</span></span>
                    </div>
                    <div class="wrong-answers">
                        <span class="label">
                            الإجابات الخاطئة
                            <svg width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M16.5197 5.65002L13.4197 3.25002C13.0197 2.85002 12.1197 2.65002 11.5197 2.65002H7.71973C6.51973 2.65002 5.21973 3.55002 4.91973 4.75002L2.51973 12.05C2.01973 13.45 2.91973 14.65 4.41973 14.65H8.41973C9.01973 14.65 9.51973 15.15 9.41973 15.85L8.91973 19.05C8.71973 19.95 9.31973 20.95 10.2197 21.25C11.0197 21.55 12.0197 21.15 12.4197 20.55L16.5197 14.45"
                                      stroke="#F5999A"
                                      stroke-width="1.5"
                                      stroke-miterlimit="10" />
                                <path d="M21.6201 5.65V15.45C21.6201 16.85 21.0201 17.35 19.6201 17.35H18.6201C17.2201 17.35 16.6201 16.85 16.6201 15.45V5.65C16.6201 4.25 17.2201 3.75 18.6201 3.75H19.6201C21.0201 3.75 21.6201 4.25 21.6201 5.65Z"
                                      stroke="#F5999A"
                                      stroke-width="1.5"
                                      stroke-linecap="round"
                                      stroke-linejoin="round" />
                            </svg>
                        </span>
                        <span>@Model.TotalQuestions / <span class="answers-count">@Model.FailAnswers</span></span>
                    </div>
                </div>
            </div>
          
        </div>

        <div class="actions col-2">
            @* <a href="#" class="btn  btn-g1">إعادة</a> *@
            <a asp-area="Customer" asp-controller="Interview" asp-action="InterviewGenerator" class="btn  btn-g1">مولد المقابلة</a>
            <a asp-area ="Customer" asp-controller="Home" asp-action="Index" class="btn btn-gray">الرئيسية</a>
        </div>

    </div>
    <h1 class="recommendation-title">التوصيات المقترحة</h1>

    <div class="recomendation-sec">
        @foreach (RecommendationDto recommendation in Model.Recommendations)
        {
              <div class="recomendation">
            <div class="content col">

                    @recommendation.Recommendation
                    @if (!string.IsNullOrEmpty(recommendation.Source))
                    {
                        <span>.....</span>
                        <a href="@recommendation.Source" class="show-more" target="_blank" rel="noopener noreferrer">لتفاصيل أكثر</a>
                    }
     
            </div>
        </div>
        }
    </div>
</section>

Muqabalati.Web/Areas/Customer/Views/Interview/StartInterview.cshtml
@model string
@{
    Layout = "_LayoutInterview.cshtml";
    ViewData["Title"] = "StartInterview";
}

@section Styles {
    <link rel="stylesheet" href="~/css/interview-ai.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/components.css" asp-append-version="true" />

}

<div  id="toneElement" style="display:none;">@Model</div>

<div class="star_container down">
    <svg width="37"
         height="43"
         viewBox="0 0 37 43"
         fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
              fill="#364C84" />
    </svg>
</div>
<div class="star_container middle-top">
    <svg width="37"
         height="43"
         viewBox="0 0 37 43"
         fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
              fill="#364C84" />
    </svg>
</div>
<div class="star_container middle-right">
    <svg width="37"
         height="43"
         viewBox="0 0 37 43"
         fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <path d="M22.2995 1.88532C22.1785 0.87461 20.84 0.592663 20.4185 1.48911L14.4008 14.2878C14.2681 14.5699 14.0092 14.765 13.7025 14.8141L0.817866 16.8761C-0.0775428 17.0194 -0.267617 18.2257 0.526562 18.7249L11.9545 25.9079C12.2266 26.0789 12.4093 26.3671 12.4474 26.6851L14.1749 41.1151C14.2959 42.1259 15.6344 42.4078 16.0559 41.5114L22.0736 28.7127C22.2063 28.4306 22.4652 28.2354 22.7719 28.1864L35.6565 26.1244C36.5519 25.9811 36.742 24.7747 35.9478 24.2756L24.5199 17.0926C24.2478 16.9216 24.0651 16.6334 24.027 16.3154L22.2995 1.88532Z"
              fill="#364C84" />
    </svg>
</div>

    <section id="interview-page" class="container">
    <a href="#" class="endInterviewBtn">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.07324 19L18.9259 5.00002M5.07328 5L18.9259 19" stroke="#171717" stroke-width="1.5" stroke-linecap="round"/>
</svg>
    </a>


        <div class="controls glass">
            <div class="timer-container">
                <div>وقت الاجابة</div>
                <div id="questionTimer">10s</div>
            </div>
            <div id="actionButtons">
                <button id="repeatQuestion" data-action="إعادة السؤال" class="btn btn-icon">
                    <svg width="25"
                         height="24"
                         viewBox="0 0 25 24"
                         fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M12.5001 22.75C7.30008 22.75 3.08008 18.52 3.08008 13.33C3.08008 11.46 3.63008 9.65 4.67008 8.09C4.90008 7.75 5.37008 7.65 5.71008 7.88C6.05008 8.11 6.15008 8.58 5.92008 8.92C5.05008 10.22 4.59008 11.75 4.59008 13.32C4.59008 17.69 8.14008 21.24 12.5101 21.24C16.8801 21.24 20.4301 17.69 20.4301 13.32C20.4301 8.95 16.8701 5.4 12.5001 5.4C11.5801 5.4 10.6801 5.53 9.83008 5.79C9.43008 5.91 9.01008 5.69 8.89008 5.29C8.77008 4.89 8.99008 4.47 9.39008 4.35C10.3901 4.05 11.4301 3.89 12.5001 3.89C17.7001 3.89 21.9201 8.12 21.9201 13.31C21.9201 18.5 17.7001 22.75 12.5001 22.75Z"
                              fill="#F4F4F4" />
                        <path d="M8.36987 6.07C8.19987 6.07 8.01987 6.01 7.87987 5.89C7.55987 5.61 7.52987 5.14 7.79987 4.83L10.6899 1.51C10.9599 1.2 11.4399 1.16 11.7499 1.44C12.0599 1.71 12.0899 2.19 11.8199 2.5L8.92987 5.81C8.77987 5.98 8.56987 6.07 8.36987 6.07Z"
                              fill="#F4F4F4" />
                        <path d="M11.7401 8.53C11.5901 8.53 11.4301 8.48 11.3001 8.39L7.92008 5.92C7.59008 5.68 7.52008 5.21 7.76008 4.88C8.00008 4.54 8.47008 4.47 8.81008 4.71L12.1801 7.17C12.5101 7.41 12.5901 7.88 12.3401 8.22C12.2001 8.43 11.9701 8.53 11.7401 8.53Z"
                              fill="#F4F4F4" />
                    </svg>
                </button>
                <button id="skipQuestion" data-action="تجاوز السؤال" class="btn btn-icon">
                    <svg width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M6.80975 20.09C6.23975 20.09 5.67976 19.94 5.15976 19.64C4.11976 19.04 3.50977 17.98 3.50977 16.78V7.21001C3.50977 6.02001 4.12976 4.95002 5.15976 4.35002C6.19976 3.75002 7.42975 3.75002 8.45975 4.35002L16.7498 9.13002C17.7798 9.73002 18.3997 10.8 18.3997 11.99C18.3997 13.18 17.7798 14.25 16.7498 14.85L8.45975 19.63C7.93975 19.94 7.37975 20.09 6.80975 20.09ZM6.80975 5.41002C6.49975 5.41002 6.18976 5.49001 5.90976 5.65001C5.34976 5.98001 5.00977 6.56001 5.00977 7.21001V16.78C5.00977 17.43 5.34976 18.01 5.90976 18.34C6.46976 18.66 7.14975 18.67 7.70975 18.34L15.9998 13.56C16.5598 13.23 16.8997 12.65 16.8997 12C16.8997 11.35 16.5598 10.77 15.9998 10.44L7.70975 5.66002C7.42975 5.50002 7.11975 5.41002 6.80975 5.41002Z" fill="#F4F4F4" />
                        <path d="M20.7402 18.9301C20.3302 18.9301 19.9902 18.5901 19.9902 18.1801V5.82007C19.9902 5.41007 20.3302 5.07007 20.7402 5.07007C21.1502 5.07007 21.4902 5.41007 21.4902 5.82007V18.1801C21.4902 18.5901 21.1602 18.9301 20.7402 18.9301Z" fill="#F4F4F4" />
                    </svg>
                </button>

            <button id="startAnswer" data-action="ابدأ الإجابة" class="btn btn-icon">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path opacity="0.4" d="M6 9.85986V14.1499" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path opacity="0.4" d="M9 8.42993V15.5699" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path opacity="0.4" d="M12 7V17" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path opacity="0.4" d="M15 8.42993V15.5699" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path opacity="0.4" d="M18 9.85986V14.1499" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="#F4F4F4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                </button>

                <button id="endAnswer" data-action="إنهاء الإجابة" class="btn btn-icon">
                    <svg width="25"
                         height="24"
                         viewBox="0 0 25 24"
                         fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M16.4998 22.3199C16.1598 22.3199 15.8298 22.22 15.5398 22.03L11.2798 19.1899H9.38977C9.15977 19.1899 8.93974 19.08 8.79974 18.9C8.65974 18.71 8.60977 18.4699 8.66977 18.2499C8.72977 18.0099 8.75977 17.7699 8.75977 17.5099C8.75977 16.7099 8.45977 15.94 7.91977 15.34C7.30977 14.65 6.43977 14.2599 5.50977 14.2599C4.61977 14.2599 3.78975 14.6099 3.17975 15.2399C2.98975 15.4399 2.69976 15.5199 2.43976 15.4399C2.17976 15.3599 1.96976 15.1499 1.90976 14.8799C1.80976 14.4399 1.75977 13.9599 1.75977 13.4399V7.43994C1.75977 3.99994 4.06977 1.68994 7.50977 1.68994H17.5098C20.9498 1.68994 23.2598 3.99994 23.2598 7.43994V13.4399C23.2598 15.1099 22.7098 16.5499 21.6598 17.5999C20.7798 18.4799 19.6098 19.01 18.2598 19.15V20.5699C18.2598 21.2199 17.8997 21.8099 17.3297 22.1199C17.0597 22.2499 16.7798 22.3199 16.4998 22.3199ZM10.2498 17.6799H11.4998C11.6498 17.6799 11.7898 17.7199 11.9198 17.8099L16.3698 20.78C16.4698 20.85 16.5698 20.8199 16.6198 20.7899C16.6698 20.7599 16.7598 20.6999 16.7598 20.5599V18.4299C16.7598 18.0199 17.0998 17.6799 17.5098 17.6799C18.7798 17.6799 19.8498 17.28 20.5998 16.53C21.3598 15.77 21.7598 14.6999 21.7598 13.4299V7.42993C21.7598 4.84993 20.0898 3.17993 17.5098 3.17993H7.50977C4.92977 3.17993 3.25977 4.84993 3.25977 7.42993V13.3099C3.93977 12.9399 4.70977 12.7499 5.50977 12.7499C6.86977 12.7499 8.15976 13.33 9.03976 14.33C9.81976 15.2 10.2598 16.3299 10.2598 17.4999C10.2498 17.5599 10.2498 17.6199 10.2498 17.6799Z"
                              fill="#F4F4F4" />
                        <path d="M5.5 22.25C4.32 22.25 3.19999 21.81 2.32999 21.02C1.97999 20.72 1.66999 20.35 1.42999 19.94C0.989993 19.22 0.75 18.37 0.75 17.5C0.75 16.25 1.23 15.08 2.09 14.19C2.99 13.26 4.2 12.75 5.5 12.75C6.86 12.75 8.15 13.33 9.03 14.33C9.81 15.2 10.25 16.33 10.25 17.5C10.25 17.88 10.2 18.26 10.1 18.62C10 19.07 9.80999 19.54 9.54999 19.95C8.71999 21.37 7.16 22.25 5.5 22.25ZM5.5 14.25C4.61 14.25 3.78001 14.6 3.17001 15.23C2.58001 15.84 2.25 16.64 2.25 17.5C2.25 18.09 2.41 18.67 2.72 19.17C2.88 19.45 3.08999 19.7 3.32999 19.91C3.92999 20.46 4.7 20.76 5.5 20.76C6.65 20.76 7.69 20.17 8.28 19.19C8.46 18.91 8.57999 18.6 8.64999 18.28C8.71999 18.02 8.75 17.77 8.75 17.51C8.75 16.71 8.45 15.94 7.91 15.34C7.31 14.64 6.43 14.25 5.5 14.25Z"
                              fill="#F4F4F4" />
                        <path d="M6.56992 19.2899C6.37992 19.2899 6.18992 19.22 6.03992 19.07L3.9299 16.96C3.6399 16.67 3.6399 16.19 3.9299 15.9C4.2199 15.61 4.6999 15.61 4.9899 15.9L7.09992 18.01C7.38992 18.3 7.38992 18.78 7.09992 19.07C6.94992 19.22 6.75992 19.2899 6.56992 19.2899Z"
                              fill="#F4F4F4" />
                        <path d="M4.43012 19.3199C4.24012 19.3199 4.05012 19.2499 3.90012 19.0999C3.61012 18.8099 3.61012 18.3299 3.90012 18.0399L6.01013 15.9299C6.30013 15.6399 6.78013 15.6399 7.07013 15.9299C7.36013 16.2199 7.36013 16.6999 7.07013 16.9899L4.96011 19.0999C4.81011 19.2499 4.62012 19.3199 4.43012 19.3199Z"
                              fill="#F4F4F4" />
                        <path d="M16 11.25H9C8.59 11.25 8.25 10.91 8.25 10.5C8.25 10.09 8.59 9.75 9 9.75H16C16.41 9.75 16.75 10.09 16.75 10.5C16.75 10.91 16.41 11.25 16 11.25Z"
                              fill="#F4F4F4" />
                    </svg>
                </button>

                <button id="pauseInterview" data-action="إيقاف المقابلة" class="btn btn-icon">
                    <svg width="25"
                         height="24"
                         viewBox="0 0 25 24"
                         fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M9.14 21.75H5.51C3.65 21.75 2.75 20.89 2.75 19.11V4.89C2.75 3.11 3.65 2.25 5.51 2.25H9.14C11 2.25 11.9 3.11 11.9 4.89V19.11C11.9 20.89 11 21.75 9.14 21.75ZM5.51 3.75C4.43 3.75 4.25 4.02 4.25 4.89V19.11C4.25 19.98 4.42 20.25 5.51 20.25H9.14C10.22 20.25 10.4 19.98 10.4 19.11V4.89C10.4 4.02 10.23 3.75 9.14 3.75H5.51Z"
                              fill="#F4F4F4" />
                        <path d="M19.4901 21.75H15.8601C14.0001 21.75 13.1001 20.89 13.1001 19.11V4.89C13.1001 3.11 14.0001 2.25 15.8601 2.25H19.4901C21.3501 2.25 22.2501 3.11 22.2501 4.89V19.11C22.2501 20.89 21.3501 21.75 19.4901 21.75ZM15.8601 3.75C14.7801 3.75 14.6001 4.02 14.6001 4.89V19.11C14.6001 19.98 14.7701 20.25 15.8601 20.25H19.4901C20.5701 20.25 20.7501 19.98 20.7501 19.11V4.89C20.7501 4.02 20.5801 3.75 19.4901 3.75H15.8601Z"
                              fill="#F4F4F4" />
                    </svg>
                </button>
            </div>
            <div id="questionNum" >?/?</div>
        </div>

        <div id="InterviewAi">
           
        <button id="prepareInterview" >ابدأ المقابلة</button>

            <div id="interviewerAIBubble" class="circle-bubble"></div>
            <div id="questionText"></div>

            <h2 id="interviewerAIState" class="display-4 mt-4">جاهز</h2>
        
        </div>

    </section>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script type="module" src="~/js/interview-ai.js"></script>
}

Muqabalati.Web/Areas/Customer/Views/Interview/_LayoutInterview.cshtml
@using BookStore.Utilties.HTMLHelpers
@using Muqabalati.Utilities.Identity
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Muqabalati.Web</title>
    <script type="importmap"></script>

    <partial name="_StyleLinksPartial"></partial>

    @await RenderSectionAsync("Styles", required: false)
</head>
<body >
    @* <div id="loading-spinner"></div> <!-- Spinner element --> *@

    <div class="glow2 top-middle"></div>
    <div class="glow2 left-middle"></div>

    @await RenderSectionAsync("Header", required: false)


    <main role ="main" id="content" class="h-full f-ctr-ctr f-col">

        <partial name="_NotificationsPartial" />
        @RenderBody()
  </main> 


    <partial name="_ScriptsPartial"></partial>
    @* <script src="~/js/interview-ai.js" asp-append-version="true"></script> *@

    <!-- Include notification.js as a module -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>